---
  - name: Revert the DNF and Grub Config back to Original
    hosts: all
    become: true
    gather_facts: false

    tasks:
      
      - name: Revert Config Files
        ansible.builtin.include_tasks: tasks/reset_configs.yml
