---
- name: In-Place Upgrade Playbook
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    vars/main.yml

  tasks:
     ## Playbook 1  ##
    - name: Tasks/Roles required for preupgrade and analysis
      block:
        - ansible.builtin.include_tasks: tasks/check_ripu_log.yml  
        - ansible.builtin.include_role:
            name: roles/analysis
        - ansible.builtin.include_tasks: handlers/main.yml

    ## Playbook 2  ##
    - name: Generate Report 
      ansible.builtin.include_tasks: tasks/generate_report.yml


    - name: Run Analyzer Role to Check for Inhibitors
      ansible.builtin.include_tasks: tasks/inhibitor_check.yml
        #register: inhibitor_result

    ## Playbook 3/4 ##
    - name: Steps required for remediation
      block:

        - ansible.builtin.include_role:
            name: roles/remediate
        - ansible.builtin.include_role:
            name: roles/analysis
        - ansible.builtin.include_tasks: handlers/main.yml

      when: inhibitors_present


    - name: Run Analyzer Role to Check for Inhibitors
      ansible.builtin.include_tasks: tasks/inhibitor_check.yml    
        #register: final_analyzer_result
 

    - name: If inhibitors still present after rememdiation, revert config files and stop playbook
      block:
    
       - ansible.builtin.include_tasks: tasks/reset_configs.yml
       - ansible.builtin.fail:
           msg: "Upgrade cannot proceed. Inhibitors still present. Reverting changes."

      when: inhibitors_present



        #    - name: Check Log and rotate if present
        #ansible.builtin.include_tasks: tasks/check_ripu_log.yml

    - name: Proceed with Upgrade Role if No Inhibitors
      ansible.builtin.include_role:
        name: roles/upgrade

    - name: Final Cleanup of Logs
      ansible.builtin.include_tasks: handlers/main.yml

    - name: Revert Config Files
      ansible.builtin.include_tasks: tasks/reset_configs.yml
