// Post Provisioning >> Network Configuration

The below instructions are for most common installations.  If you are building things in the cloud instances (AWS, Azure) the instructions will be different, but these should be mostly applicable.

= Configure Server Hostname

. Log into the host using the *VMWare Console* using the host appropriate account and gain *root* access
+
NOTE: You can also *SSH* to the system using putty if the IPV4 address is known

. Change the system hostname
+
[source,console]
----
# hostnamectl set-hostname <hostname>.<domain>
----

= Configure Server Network

. Display Connection Information
+
[source,console]
----
# nmcli con show
----
+
.Sample results
[source,bash]
----
NAME    UUID                                  TYPE      DEVICE
ens192  e5e3bcf1-f30d-4e99-b0fa-80b400b45632  ethernet  ens192
----
+
IMPORTANT: The *NAME* above is the *PROFILE* used in the _nmcli_ commands as below

. Setup the IPV4 connection
+
.IPV4 Configuration
[source,console]
----
# nmcli con mod ens192 ipv4.method manual ipv4.address <static ip>/<cidr> // <1>
# nmcli con mod ens192 ipv4.gateway <gateway ip> // <2>
# nmcli con mod ens192 ipv4.dns "<dns server ip(s)>" // <3>
# nmcli con mod ens192 ipv4.dns-search "<search domain(s)>" // <4>
# nmcli con mod ens192 connection.autoconnect yes <5>
# nmcli con up ens192 // <6>
----
<1> Set connection to be manual (statically) configured, set the static IP address with the CIDR assigned to the host
<2> Gateway IP for the Static IP Network
<3> Local DNS Server(s)
<4> DNS Search Domain(s)
<5> Ensure the connection autostarts on boot
<6> Start the connection

. Disconnect from Console

= Static IP - DHCP Reservation

NOTE: The current environment uses DHCP through infoblox as the primary means of IP allocation.  When assigning static IPs to RHEL systems, the DHCP address provided must be configured for a reservation to ensure it is not assigned to another system.

. Gather the MAC address and IP of the interface
+
[source,console]
----
# nmcli dev show ens192 | egrep "GENERAL.HWADDR|IP4.ADDRESS"
----
+
Example Output:
+
....
GENERAL.HWADDR:                         00:50:56:BC:74:B7
IP4.ADDRESS[1]:                         172.20.4.148/24
....

. Configure Infoblox to ensure you have a Static IP set
+
NOTE: Static IPs in Infoblox must be configured as a `reservation`
+
NOTE: If you would like a DHCP reservation you must configured Infoblox to use a `fixed address` and enter the provided MAC address


