// Post Provisioning >> Account Configuration

WARNING: SOCOM enterprise does not current have any centralized management of user identity on any enclave.  As such all user accounts must be managed individually on the hosts and passwords must be changed every 90 days according to policy.

Initial login is provided by the `tempadmin` account.  This account is exactly as its name implies, a temporary admin account.  Its purpose is to allow users to log in one time initially to set up their system.

NOTE: It is expected that you will create local admin accounts as needed and remove the `tempadmin` account after sufficient access has been granted.

= Creating new admin account

. Log into the system using the `tempadmin` account (or another admin account already created) and gain root access

. Create the new user `<username>` ensuring the home directory is created
+
[source,console]
----
# useradd -m <username>
----

. Set a temporary password for the user
+
[source,console]
----
# passwd <username>
----
+
Input password twice to confirm

. Enable admin privileges to the account by adding it to the `wheel` group
+
[source,console]
----
# usermod -aG wheel <username>
----

. Expire the password for the user
+
[source,console]
----
# passwd -e <username>
----

. Have the user log into the system and change their password


