---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true

  vars:
    leapp_upgrade_opts: --target 9.4
    update_grub_to_grub_2: true
    selinux_mode: permissive
    infra_leapp_upgrade_system_roles_collection: 'redhat.rhel_system_roles'
    post_upgrade_release: '9.4'
    set_crypto_policies: false

  tasks:

    - name: Check that Log file Does not Already Exist
      ansible.builtin.include_tasks: ../tasks/check_ripu_log.yml
  
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: ../roles/upgrade

    - name: Final Cleanup of Logs
      ansible.builtin.include_tasks: handlers/main.yml
...
